#define HOEHE 30
#define BREITE 50
#define ANZAHL_FUTTER 10
#define ANZAHL_VERTIKALE_WAENDE 5
#define ANZAHL_HORIZONTALE_WAENDE 5
#define ANZAHL_DIAGONALE_WAENDE 5
#define WAND_LAENGE 6
#define START_AREA 6
#define MAX_SCHLANGE_LAENGE 100
#define START_SCHLANGE_LAENGE 5

#define LEER ' '
#define RAND '#'
#define FUTTER 'o'
#define SCHLANGEN_KOPF '@'
#define HINDERNIS '#'
#define SCHLANGEN_STUECK '+'